name: Veldrid CI build

on:
  create: # when tags are created
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:
    runs-on: windows-latest # for DirectX

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Exclude projects
      working-directory: ./src
      run: >
        dotnet sln remove
        Veldrid.Tests.Android/Veldrid.Tests.Android.csproj

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build --no-restore src

    - name: Test
      run: dotnet test --no-build --verbosity normal src --filter "Backend=D3D11"

    - name: Build Packages
      run: dotnet pack src -c Release

    - name: Publish tagged release to nuget.org
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push bin\Packages\Release\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}

    - name: Generate GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin\Packages\Release\*.nupkg
